# Generated by Django 2.2.5 on 2019-10-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adTitle', models.CharField(max_length=250)),
                ('adDescription', models.TextField()),
                ('adMedia', models.FileField(upload_to='adfiles/%Y/')),
                ('nStoreLocator', models.CharField(max_length=300)),
                ('clientName', models.CharField(max_length=250)),
            ],
        ),
    ]
