# Generated by Django 2.2.5 on 2019-10-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvMgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='timesPlayed',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
