# Generated by Django 2.2.5 on 2019-10-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvMgmt', '0002_adv_timesplayed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adv',
            options={'verbose_name': 'Advert', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AlterField(
            model_name='adv',
            name='adDescription',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='adMedia',
            field=models.FileField(upload_to='adfiles/%Y/', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='adTitle',
            field=models.CharField(max_length=250, verbose_name='Ad. Title'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='clientName',
            field=models.CharField(max_length=250, verbose_name='Name of Client'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='nStoreLocator',
            field=models.CharField(max_length=300, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='timesPlayed',
            field=models.PositiveIntegerField(verbose_name='Times Played'),
        ),
    ]
