# Generated by Django 2.2.6 on 2019-11-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvMgmt', '0003_auto_20191028_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='timesPlayed',
            field=models.PositiveIntegerField(default=0, verbose_name='Times Played'),
        ),
    ]
