# Generated by Django 2.2.6 on 2019-11-15 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceNumber', models.CharField(max_length=200, verbose_name='Device ID')),
                ('carRegNumber', models.CharField(max_length=6, verbose_name='Registration Number')),
                ('carOwner', models.CharField(max_length=500, verbose_name='Car Owner')),
                ('carDriver', models.CharField(max_length=500, verbose_name='Car Driver')),
                ('carModel', models.CharField(max_length=250, verbose_name='Car Model')),
                ('activeFlag', models.BooleanField(verbose_name='Online')),
                ('longitude', models.DecimalField(decimal_places=7, default=-26.1929, max_digits=10, null='true', verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=7, default=28.0305, max_digits=10, null='true', verbose_name='Latitude')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
