# Generated by Django 2.2.6 on 2019-11-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgmt', '0002_screen_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='control',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
