# Generated by Django 2.2.6 on 2019-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgmt', '0003_auto_20191115_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='lastknown',
            field=models.CharField(default='Johannesburg', max_length=500, verbose_name='Last Known'),
        ),
    ]
