# Generated by Django 2.2.6 on 2019-11-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgmt', '0004_screen_lastknown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='control',
        ),
    ]
