# Generated by Django 2.2.6 on 2019-11-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssetMgmt', '0004_screen_lastknown'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Asset Detail',
                'verbose_name_plural': 'Asset Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('AssetMgmt.screen',),
        ),
    ]
